audios:
    path:     /
    defaults: { _controller: "AppBundle:Audio:index" }

audios_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Audio:show" }

audios_new:
    path:     /new
    defaults: { _controller: "AppBundle:Audio:new" }

audios_create:
    path:     /create
    defaults: { _controller: "AppBundle:Audio:create" }
    methods:  POST

audios_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Audio:edit" }

audios_update:
    path:     /{id}/update
    defaults: { _controller: "AppBundle:Audio:update" }
    methods:  [POST, PUT]

audios_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Audio:delete" }
    methods:  [POST, DELETE]
