login:
    path:     /login
    defaults: { _controller: LoginBundle:Login:login }

check_user:
    path:     /login/check_user
    defaults: { _controller: LoginBundle:Login:checkUser}

login_check:
    path: /login_check

register_register:
    path:     /register
    defaults: { _controller: LoginBundle:Register:register }

register_create:
    path:     /register/create
    defaults: { _controller: LoginBundle:Register:create }